---
title: "Pneumonia"
author: "Graham Chickering"
date: "11/13/2020"
output: pdf_document
---

```{r, message=FALSE}
library(tensorflow)
library(tfdatasets)
library(keras)
library(cloudml)
library(readr) 
library(tidyverse)
library(googleCloudStorageR)
library(googleAuthR)
library(sparklyr)
library(magick)
library(ggplot2)
library(cowplot)
library(reprex)
library(imager)
```


```{r}
gcs_auth(json_file="account_credentials.json")
gcs_list_buckets("image-analysis-detection")
```


```{r}
# gcs_get_bucket("chest-xray-train")   
# gcs_global_bucket("chest-xray-train")
# train_objects <- gcs_list_objects() %>% mutate(id= row_number())
# 
# gcs_get_bucket("chest-xray-validation")   
# gcs_global_bucket("chest-xray-validation")
# validation_objects <- gcs_list_objects() %>% mutate(id= row_number())
# 
# gcs_get_bucket("chest-xray-test")   
# gcs_global_bucket("chest-xray-test")
# test_objects <- gcs_list_objects() %>% mutate(id= row_number())
```

```{r}
 gcs_get_bucket("chest-xray-medical")   
 gcs_global_bucket("chest-xray-medical")
all_objects <- gcs_list_objects() %>% mutate(id= row_number())
length(all_objects)

#trial<-gcs_get_object(all_objects)
#image<-gcs_get_object(all_objects$name[[1]])
```
```{r}
# data_dir <- get_file(
#   origin = "https://console.cloud.google.com/storage/browser/chest-xray-medical;tab=objects?forceOnBucketsSortingFiltering=false&project=image-analysis-detection&prefix=&forceOnObjectsSortingFiltering=false",
#   fname = "chest_xray",
#   extract = TRUE
# )
# data_dir <- file.path(dirname(data_dir), "medical_photos")
# images <- list.files(data_dir, pattern = ".jpg", recursive = TRUE)

# data_dir <- get_file(
#   origin = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz",
#   fname = "flower_photos.tgz",
#   extract = TRUE
# )
#trial_dir<-file.path(all_objects)

data_dir <- file.path("/Users/grahamchickering/Downloads/chest_xray")
images <- list.files(data_dir, pattern = ".jpeg", recursive = TRUE)
length(images)

classes <- list.dirs(data_dir, full.names = FALSE, recursive = FALSE)
classes
```

```{r}
list_ds <- file_list_dataset(file_pattern = paste0(data_dir, "/*/*/*"))
list_ds %>% reticulate::as_iterator() %>% reticulate::iter_next()
```

```{r}
get_label <- function(file_path) {
  parts <- tf$strings$split(file_path, "/")
  parts[-2] %>% 
    tf$equal(classes) %>% 
    tf$cast(dtype = tf$float32)
}

decode_img <- function(file_path, height = 224, width = 224) {
  
  size <- as.integer(c(height, width))
  
  file_path %>% 
    tf$io$read_file() %>% 
    tf$image$decode_jpeg(channels = 3) %>% 
    tf$image$convert_image_dtype(dtype = tf$float32) %>% 
    tf$image$resize(size = size)
}

preprocess_path <- function(file_path) {
  list(
    decode_img(file_path),
    get_label(file_path)
  )
}
```

```{r}
labeled_ds <- list_ds %>% 
  dataset_map(preprocess_path, num_parallel_calls = tf$data$experimental$AUTOTUNE)

labeled_ds %>% 
  reticulate::as_iterator() %>% 
  reticulate::iter_next()
```

```{r}
install.packages("cloudml")
```

```{r}
library(cloudml)
gcloud_install()
```

```{r}
# gcloud_init()
# data_dir <- gs_data_dir("gs://chest-xray-medical/chest_xray")
# gs_rsync("gs://chest-xray-medical/chest_xray", destination= "/Users/grahamchickering/Desktop/Stat 495/STAT495F20-project-Chickering/data-raw/data")
# 
# gs_data_dir_local("gs://chest-xray-medical/chest_xray")
```

