---
title: "sparklyr example"
author: "Nicholas Horton (nhorton@amherst.edu)"
date: "October 30, 2020"
output: 
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

The `sparklyr` package facilitates access to Spark clusters from within RStudio at hadoop2-rstudio.amherst.edu.  See http://spark.rstudio.com for details of the implementation.

```{r}
# install.packages("tensorflow")
# install.packages("remotes")
# devtools::install_github("rstudio/keras")
# devtools::install_github("sparklyr/sparklyr")
#spark_install()
library(sparklyr)
spark_install(version = "2.1.0")
```


```{r, setup, include=FALSE}
library(sparklyr)
sc <- spark_connect(master = "local")
```

```{r}
library(sparktf)
library(tensorflow)
library(keras)
```

```{r}
train_image_files_path <- file.path("/Users/grahamchickering/Downloads/chest_xray/train")
spark_read_tfrecord(sc, train_image_files_path)
```


```{r}
spark_disconnect(sc)
```


