---
title: "Pneumonia"
author: "Graham Chickering"
date: "11/13/2020"
output: pdf_document
---

```{r, message=FALSE}
library(tensorflow)
library(reticulate) 
# library(tfdatasets)
library(keras)
#library(cloudml)
# library(tidyverse)
# library(sparklyr)
# library(ggplot2)
# library(readr) 
library(tictoc)
#library(rsparkling)
#library(h2o)
```


```{r}
chest_list <- c("NORMAL","PNEUMONIA")
output_n<-length(chest_list)

img_width <- 20
img_height <- 20
target_size <- c(img_width, img_height)

# RGB = 3 channels
channels <- 1

batch_size<-10

# path to image folders
#train_image_files_path<- file.path("/Users/grahamchickering/Downloads/chest_xray/val")
train_image_files_path <- file.path("/Users/grahamchickering/Downloads/chest_xray/train")
#val_image_files_path <- file.path("/Users/grahamchickering/Downloads/chest_xray/val")
#test_image_files_path<-file.path("/Users/grahamchickering/Downloads/chest_xray/test")
```

```{r, message=FALSE}
train_data_gen = image_data_generator(
  rescale = 1/255,
  validation_split=0.2
)
```

```{r}
train_image_array_gen <- flow_images_from_directory(train_image_files_path, 
                                          train_data_gen,
                                          subset = 'training',
                                          target_size = target_size,
                                          color_mode="grayscale",
                                          class_mode = "binary",
                                          classes = chest_list,
                                          shuffle=TRUE,
                                          batch_size=batch_size,
                                          seed = 27)

val_image_array_gen <- flow_images_from_directory(train_image_files_path, 
                                          train_data_gen,
                                          subset = 'validation',
                                          color_mode="grayscale",
                                          target_size = target_size,
                                          class_mode = "binary",
                                          classes = chest_list,
                                          shuffle=TRUE,
                                          batch_size=batch_size,
                                          seed = 27)
# test_image_array_gen <- flow_images_from_directory(test_image_files_path, 
#                                           test_data_gen,
#                                           target_size = target_size,
#                                           subset='testing',
#                                           class_mode = "categorical",
#                                           classes = chest_list,
#                                           batch_size=batch_size,
#                                           seed = 27)
```

```{r}
table(factor(train_image_array_gen$classes))
table(factor(val_image_array_gen$classes))
```

```{r}
cat("\nClass label vs index mapping:\n")
train_image_array_gen$class_indices
```

```{r}
chest_classes_indices <- train_image_array_gen$class_indices
save(chest_classes_indices, file ="chest_indices.Rdata")
```


```{r}
# number of training samples
train_samples <- train_image_array_gen$n
# number of validation samples
valid_samples <- val_image_array_gen$n

# define batch size and number of epochs
batch_size <- 32
epochs <- 5
```

```{r}
model <- keras_model_sequential() %>% 
  layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = "relu", 
                input_shape = c(20,20,1)) %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu") %>% 
  layer_max_pooling_2d(pool_size = c(2,2)) %>% 
  layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = "relu")

model %>% 
  layer_flatten() %>% 
  layer_dense(units = 64, activation = "relu") %>% 
  layer_dense(units = 10, activation = "softmax")

```

```{r}
model %>% compile(
  optimizer = "adam",
  loss = "sparse_categorical_crossentropy",
  metrics = "accuracy"
)
summary(model)
```

```{r}
tensorboard("logs/run_a")
hist <- model %>% fit_generator(
  callbacks = callback_tensorboard("logs/run_a"),
  # training data
  train_image_array_gen,
  # epochs
  steps_per_epoch = as.integer(train_samples / batch_size), 
  epochs = epochs, 
  
  # validation data
  validation_data = val_image_array_gen,
  validation_steps = as.integer(valid_samples / batch_size)
)
```

```{r}
plot(hist)
```
```{r}
model %>% save_model_hdf5("my_model.h5")
model <- load_model_hdf5("my_model.h5")
```

##Testing the model
```{r}
 test_image_files_path<-file.path("/Users/grahamchickering/Downloads/chest_xray/test")
```

```{r}
test_datagen <- image_data_generator(rescale = 1/255)

test_generator <- flow_images_from_directory(
        test_image_files_path,
        test_datagen,
        color_mode="grayscale",
        target_size = target_size,
        class_mode = "binary",
        classes = chest_list,
        batch_size = 1,
        shuffle = FALSE,
        seed = 42)
```

```{r, warning=FALSE, message=FALSE}
model %>%
  evaluate_generator(test_generator, 
                     steps = as.integer(test_generator$n))
```
```{r}
classes <- test_generator$classes %>%
  factor() %>%
  table() %>%
  as_tibble()
colnames(classes)[1] <- "value"
classes
```

```{r}
indices <- test_generator$class_indices %>%
  as.data.frame() %>%
  gather() %>%
  mutate(value = as.character(value)) %>%
  left_join(classes, by = "value")
indices
```

```{r}
test_generator$reset()
predictions <- model %>% 
  predict_generator(
    generator = test_generator,
    steps = as.integer(test_generator$n)
    ) %>%
  round(digits = 2) %>%
  as_tibble()
predictions

colnames(predictions) <- indices$key
predictions
predictions <- predictions %>%
   mutate(truth_idx = as.character(test_generator$classes)) %>%
   left_join(indices, by = c("truth_idx" = "value"))
```

